apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer-preview
spec:
  type: LoadBalancer
  selector:
    app: nginx-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
